### ISSUE TITLE
Torque Executor Provider doesn't work with nodes option

### ISSUE THREAD

**Issue by enrush01** [Parsl/libsubmit#63]
use config

block: {
nodes:2
task blocks: 2
walltime:00:05:00
initBlocks: 1
minBlocks: 1
maxBlocks: 1
}
The torque provider doesn't write a submit script that uses the nodes option.

ie. In the template for torque, the $nodes variable doesn't appear.

**Comment by yadudoc** [comment]
Hi @enrush01, Are you using libsubmit as is, or using it via Parsl ?
Torque and aprun launchers have been heavily updated in preparation for the 0.5.0 release, and this bug is fixed in the new codebase. I would recommend you wait till the 0.5.0 release is available, or if you are okay with trying code that is not fully documented, 0.5.0a1 is available on pypi

**Comment by enrush01** [comment]
Thanks for the hard work! My team is enjoying using Parsl.
